<?php

namespace Nurdaulet\FluxWallet\Services\Payment;

use Nurdaulet\FluxWallet\Services\Payment\Providers\Epay\EpayServiceProvider;
use Nurdaulet\FluxWallet\Services\Payment\Providers\OneVision\OneVisionServiceProvider;
use Nurdaulet\FluxWallet\Services\Payment\Providers\Paybox\PayboxServiceProvider;

use Illuminate\Support\ServiceProvider;

class PaymentServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('paymentService', PaymentService::class);
        $this->app->register(PayboxServiceProvider::class);
        $this->app->register(EpayServiceProvider::class);
        $this->app->register(OneVisionServiceProvider::class);
    }
}
