<?php

namespace Nurdaulet\FluxWallet;


use Nurdaulet\FluxWallet\Services\Payment\Providers\Paybox\PayboxServiceProvider;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Artisan;
use Nurdaulet\FluxWallet\Helpers\TextConverterHelper;
use Illuminate\Support\ServiceProvider;
use Nurdaulet\FluxWallet\Services\Payment\PaymentService;
use Nurdaulet\FluxWallet\Services\Payment\Providers\Epay\EpayServiceProvider;
use Nurdaulet\FluxWallet\Services\Payment\Providers\OneVision\OneVisionServiceProvider;
use Nurdaulet\FluxWallet\Services\WalletFacadeService;

class FluxWalletServiceProvider extends ServiceProvider
{

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->publishConfig();
            $this->publishMigrations();
        }
        $this->loadRoutesFrom(__DIR__ . '/../routes/api.php');
        $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');


    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('paymentService', PaymentService::class);
        $this->app->register(PayboxServiceProvider::class);
        $this->app->register(EpayServiceProvider::class);
        $this->app->register(OneVisionServiceProvider::class);

        $this->mergeConfigFrom(
            __DIR__.'/../config/flux-wallet.php',
            'flux-wallet'
        );
        $this->app->bind('textConverter', TextConverterHelper::class);
        $this->app->bind('wallet', WalletFacadeService::class);
//        $this->app->bind('stringFormatter', StringFormatterHelper::class);
    }

    protected function publishConfig()
    {
        $this->publishes([
            __DIR__.'/../resources/views' => resource_path('views/vendor'),
            __DIR__ . '/../config/flux-wallet.php' => config_path('flux-wallet.php'),
        ], 'flux-wallet-config');


//        if (!file_exists(config_path('flux-wallet.php'))) {
//            Artisan::call('vendor:publish', ['--tag' => 'flux-wallet-config']);
//        }
    }

    protected function publishMigrations()
    {

        $this->publishes([
            __DIR__ . '/../database/migrations/check_balances_table.php.stub' => $this->getMigrationFileName(0,'check_flux_wallet_balances_table.php'),
            __DIR__ . '/../database/migrations/check_bankcards_table.php.stub' => $this->getMigrationFileName(1,'check_flux_wallet_bankcards_table.php'),
            __DIR__ . '/../database/migrations/check_transactions_table.php.stub' => $this->getMigrationFileName(2,'check_flux_wallet_transactions_table.php'),
        ], 'flux-wallet-migrations');
    }

    /**
     * Returns existing migration file if found, else uses the current timestamp.
     */
    protected function getMigrationFileName($index, string $migrationFileName): string
    {
        $timestamp = date('Y_m_d_His');

        $filesystem = $this->app->make(Filesystem::class);

        return Collection::make([$this->app->databasePath() . DIRECTORY_SEPARATOR . 'migrations' . DIRECTORY_SEPARATOR])
            ->flatMap(fn($path) => $filesystem->glob($path . '*_' . $migrationFileName))
            ->push($this->app->databasePath() . "/migrations/{$timestamp}{$index}_{$migrationFileName}")
            ->first();
    }
}
