<?php

namespace Nurdaulet\FluxWallet\Services\Payment\Providers\Epay;

use Nurdaulet\FluxWallet\Repositories\BankcardRepository;
use Illuminate\Support\ServiceProvider;

class EpayServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('epayService', function () {
            return new EpayService(new EpayRepository(), new BankcardRepository());
        });
    }
}
